-- CreateTable
CREATE TABLE "CONVITES_VISITA" (
    "id" SERIAL NOT NULL,
    "codigo" TEXT NOT NULL,
    "expira_em" TIMESTAMP(3) NOT NULL,
    "usada" BOOLEAN NOT NULL DEFAULT false,
    "morador_id" INTEGER NOT NULL,
    "unidade_id" INTEGER NOT NULL,
    "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CONVITES_VISITA_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CONVITES_VISITA_codigo_key" ON "CONVITES_VISITA"("codigo");

-- AddForeignKey
ALTER TABLE "CONVITES_VISITA" ADD CONSTRAINT "CONVITES_VISITA_morador_id_fkey" FOREIGN KEY ("morador_id") REFERENCES "MORADORES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CONVITES_VISITA" ADD CONSTRAINT "CONVITES_VISITA_unidade_id_fkey" FOREIGN KEY ("unidade_id") REFERENCES "UNIDADES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
