-- CreateTable
CREATE TABLE "RECUPERACOES_SENHA" (
    "id" SERIAL NOT NULL,
    "usuario_id" INTEGER NOT NULL,
    "codigo" TEXT NOT NULL,
    "expira_em" TIMESTAMP(3) NOT NULL,
    "usada" BOOLEAN NOT NULL DEFAULT false,
    "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RECUPERACOES_SENHA_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "RECUPERACOES_SENHA" ADD CONSTRAINT "RECUPERACOES_SENHA_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
