-- CreateTable
CREATE TABLE "VISITANTES" (
    "id" SERIAL NOT NULL,
    "nome_completo" TEXT NOT NULL,
    "cpf" TEXT,
    "rg" TEXT,
    "celular" TEXT,

    CONSTRAINT "VISITANTES_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VISITAS" (
    "id" SERIAL NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PRE_CADASTRADO',
    "data_previsao" TIMESTAMP(3),
    "visitante_id" INTEGER NOT NULL,
    "morador_id" INTEGER NOT NULL,
    "unidade_id" INTEGER NOT NULL,

    CONSTRAINT "VISITAS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "REGISTROS_ACESSO" (
    "id" SERIAL NOT NULL,
    "tipo" TEXT NOT NULL,
    "data_hora" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "morador_id" INTEGER,
    "visitante_id" INTEGER,
    "unidade_id" INTEGER NOT NULL,

    CONSTRAINT "REGISTROS_ACESSO_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "VISITANTES_cpf_key" ON "VISITANTES"("cpf");

-- AddForeignKey
ALTER TABLE "VISITAS" ADD CONSTRAINT "VISITAS_visitante_id_fkey" FOREIGN KEY ("visitante_id") REFERENCES "VISITANTES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VISITAS" ADD CONSTRAINT "VISITAS_morador_id_fkey" FOREIGN KEY ("morador_id") REFERENCES "MORADORES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VISITAS" ADD CONSTRAINT "VISITAS_unidade_id_fkey" FOREIGN KEY ("unidade_id") REFERENCES "UNIDADES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REGISTROS_ACESSO" ADD CONSTRAINT "REGISTROS_ACESSO_morador_id_fkey" FOREIGN KEY ("morador_id") REFERENCES "MORADORES"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REGISTROS_ACESSO" ADD CONSTRAINT "REGISTROS_ACESSO_visitante_id_fkey" FOREIGN KEY ("visitante_id") REFERENCES "VISITANTES"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REGISTROS_ACESSO" ADD CONSTRAINT "REGISTROS_ACESSO_unidade_id_fkey" FOREIGN KEY ("unidade_id") REFERENCES "UNIDADES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
